name: crazyswarm3
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - vispy
  - pyyaml
  - swig
  - sphinx
  - sphinx_rtd_theme
  - pyqt
  - sphinx-argparse
  - pytest
