name: crazyswarm
channels:
  - omnia  # For package quadprog.
dependencies:
  - python=2.7
  - numpy
  - matplotlib
  - vispy
  - pyyaml
  - swig
  - sphinx
  - sphinx_rtd_theme
  - pyqt
  - quadprog
  - scipy
