name: Crazyswarm Sim-Only Conda CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Conda
      uses: goanpeca/setup-miniconda@v1
      with:
        environment-file: conda_env.yaml
        activate-environment: crazyswarm

    - name: Build
      run: |
        ./buildSimOnly.sh

    - name: Test
      run: |
        cd ros_ws/src/crazyswarm/scripts
        python -m pytest
